workflows:
  ios-unsigned:
    name: iOS unsigned build
    instance_type: mac_mini_m2
    max_build_duration: 60

    working_directory: rpmont-conferencia-app

    environment:
      xcode: 16.4
      node: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Lint
        script: |
          npm run lint

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build iOS simulator app
        working_directory: rpmont-conferencia-app/ios/App
        script: |
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            build

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
      - /tmp/xcodebuild_logs/*.log


  ios-device-unsigned:
    name: iOS device unsigned build
    instance_type: mac_mini_m2
    max_build_duration: 60

    working_directory: rpmont-conferencia-app

    environment:
      xcode: 16.4
      node: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Lint
        script: |
          npm run lint

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build iOS device app
        working_directory: rpmont-conferencia-app/ios/App
        script: |
          rm -rf build

          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

      - name: Create unsigned IPA
        working_directory: rpmont-conferencia-app/ios/App
        script: |
          mkdir -p build/ipa/Payload

          cp -R \
            build/DerivedData/Build/Products/Debug-iphoneos/App.app \
            build/ipa/Payload/App.app

          cd build/ipa

          zip -r \
            RPMont-Gestao-unsigned.ipa \
            Payload

    artifacts:
      - $CM_BUILD_DIR/rpmont-conferencia-app/ios/App/build/ipa/*.ipa
      - $CM_BUILD_DIR/rpmont-conferencia-app/ios/App/build/DerivedData/Build/Products/Debug-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log