spring.application.name=conferencia-api

server.address=0.0.0.0
server.port=8080

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false